3lvia/designsystem

packages/web/src/styles.scss
https://elvia.atlassian.net/browse/LEGO-3405
=> fix(web): change max width for desktop

packages/vue-test/index.html, packages/vue-test/src/main.ts, packages/vue-test/src/styles.scss
=> chore(vue-test): use elvis from npm, not cdn

packages/web/src/app/shell/page-with-sidenav/page-with-sidenav.component.scss
https://elvia.atlassian.net/browse/LEGO-3409
=> fix(web): fix breakpoint for max desktop width on web

packages/web/src/app/shared/component-documentation/component-changelog/component-changelog-id-pipe.ts, packages/web/src/app/shared/component-documentation/component-changelog/component-changelog.component.ts
Should fix https://github.com/3lvia/designsystem/security/code-scanning/1
=> fix(component-changelog-id.pipe): double escape of &

packages/elvis/.internal/classlist.json, packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/percy/components/input.html, packages/elvis/src/components/form/input.scss, packages/web/src/app/doc-pages/components/forms/input-doc/input-doc.component.html, packages/web/src/app/doc-pages/components/forms/input-doc/input-doc.component.ts, packages/web/src/app/doc-pages/components/forms/input-doc/input-suffix-ceg/input-suffix-ceg.component.html, packages/web/src/app/doc-pages/components/forms/input-doc/input-suffix-ceg/input-suffix-ceg.component.scss, packages/web/src/app/doc-pages/components/forms/input-doc/input-suffix-ceg/input-suffix-ceg.component.ts
https://elvia.atlassian.net/browse/LEGO-2680
=> Lego 2680 suffiks i input css biblioteket

packages/components/components/elvis-dropdown/CHANGELOG.json, packages/components/components/elvis-dropdown/package.json, packages/components/components/elvis-dropdown/src/react/elvia-dropdown.tsx, packages/components/components/elvis-toolbox/CHANGELOG.json, packages/components/components/elvis-toolbox/package.json, packages/components/components/elvis-toolbox/src/hooks/useConnectedOverlay.ts, packages/web/src/app/dev/v2-playground/v2-playground.component.ts, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3412
=> Lego 3412 dropdown la overlay bli bredere enn inputfelt

packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.html, packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.scss, packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.ts
https://elvia.atlassian.net/browse/LEGO-3205
=> docs(elvis): update documentation of elvis installation

packages/components/components/elvis-spotlight/CHANGELOG.json, packages/components/components/elvis-spotlight/package.json, packages/components/components/elvis-spotlight/src/react/elvia-spotlight.tsx, packages/components/components/elvis-spotlight/src/react/styledComponents.tsx
https://elvia.atlassian.net/browse/LEGO-3416
=> Lego 3416 spotlight dekker ikke hele bredden nar man forstorrer vindu

packages/components/components/elvis-datepicker-range/CHANGELOG.json, packages/components/components/elvis-datepicker-range/package.json, packages/components/components/elvis-datepicker-range/src/react/elvia-datepicker-range.test.tsx, packages/components/components/elvis-datepicker-range/src/react/elvia-datepicker-range.tsx, packages/components/components/elvis-datepicker/CHANGELOG.json, packages/components/components/elvis-datepicker/package.json, packages/components/components/elvis-datepicker/src/react/elvia-datepicker.test.tsx, packages/components/components/elvis-datepicker/src/react/elvia-datepicker.tsx, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3417?atlOrigin=eyJpIjoiODc2OWEyM2Y1MjE1NDE0ZDkxYjNjNWVjYjM2YzYxNDgiLCJwIjoiaiJ9
=> LEGO-3417 datepicker valueOnChangeISOString gir klokkeslett

packages/components/components/elvis-datepicker-range/src/react/dateHelpers.ts, packages/components/components/elvis-datepicker/src/react/dateHelpers.ts
=> chore(dateHelpers): improve type of isValidDate

yarn.lock
=> chore(deps): yarn dedupe

packages/components/build/esbuild.config.ts
=> feat(build): add watch clean support

packages/web/src/app/doc-pages/components/dropdown-doc/dropdown-doc.component.html
https://elvia.atlassian.net/browse/LEGO-3411
=> docs(dropdown): fix status icons alignment

packages/components/components/elvis-header/CHANGELOG.json, packages/components/components/elvis-header/package.json, packages/components/components/elvis-header/src/react/elviaApps.ts
https://elvia.atlassian.net/browse/LEGO-3419
=> feat(header): add OneTime to app drawer

packages/web/src/app/core/services/cms/cms.service.ts, packages/web/src/app/doc-pages/cms/cms-page/cms-page.component.ts
https://elvia.atlassian.net/browse/LEGO-3418
=> fix(web): dont use contentful preview API locally

packages/components/components/elvis-modal/CHANGELOG.json, packages/components/components/elvis-modal/package.json, packages/components/components/elvis-modal/src/react/styledComponents.tsx
https://elvia.atlassian.net/browse/LEGO-3429
=> fix(modal): fix max  height of mobile modal

packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/percy/components/input.html, packages/elvis/src/components/form/input.scss, packages/web/src/app/dev/v2-playground/v2-playground.component.html
https://elvia.atlassian.net/browse/LEGO-3427
=> fix(input): fix disabled state in small input form fields

packages/components/components/elvis-stepper/CHANGELOG.json, packages/components/components/elvis-stepper/package.json, packages/components/components/elvis-stepper/src/react/StepContent.tsx, packages/components/components/elvis-stepper/src/react/publicApi.public.ts, packages/components/components/elvis-toolbox/CHANGELOG.json, packages/components/components/elvis-toolbox/package.json, packages/components/components/elvis-toolbox/src/components/button/button.tsx, packages/web/src/app/dev/v2-playground/v2-playground.component.html, packages/web/src/app/doc-pages/components/stepper-doc/stepper-data.ts, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3434
=> feat(stepper): add loading state to next button in stepper

packages/web/src/app/shared/component-documentation/ceg/code-generator/code-generator.component.html, packages/web/src/app/shared/component-documentation/ceg/code-generator/code-generator.component.ts, packages/web/src/app/shared/component-documentation/component-installation/component-installation.component.ts, packages/web/src/app/shared/component-documentation/preferredLanguage.service.ts, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3436
=> fix(web): fix issues with segmented control in installation guide

packages/web/src/app/shared/user-questionnaire/user-questionnaire.component.ts
=> fix(web-user-questionnaire): only open modal on design.elvia.io

packages/components/package.json, yarn.lock
=> chore(deps): update @testing-library/react

.github/workflows/yarnDedupe.yml
=> feat(ci): add github action to create yarn dedupe PR

packages/web/src/app/doc-pages/about/get-started-doc/get-started-doc.component.html, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-installation/illustrations-installation.component.html, packages/web/src/app/doc-pages/components/css-library-doc/css-library-doc.component.html, packages/web/src/app/shared/component-documentation/component-installation/component-installation.component.html
https://elvia.atlassian.net/browse/LEGO-3444
=> Lego 3444 get started sma oppdateringer pa seksjoner i get started og stilbiblioteket

packages/components/components/elvis-stepper/CHANGELOG.json, packages/components/components/elvis-stepper/package.json, packages/components/components/elvis-stepper/src/react/StepContent.tsx, packages/components/components/elvis-stepper/src/react/elvia-stepper-horizontal.tsx, packages/components/components/elvis-stepper/src/react/elvia-stepper-vertical.tsx, packages/components/components/elvis-stepper/src/react/elvia-stepper.test.tsx, packages/components/components/elvis-stepper/src/react/elvia-stepper.tsx, packages/components/components/elvis-stepper/src/react/elvia-stepper.types.ts, packages/web/src/app/dev/v2-playground/v2-playground.component.html, packages/web/src/app/doc-pages/components/stepper-doc/stepper-data.ts, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3448
=> Lego 3448 stepper callback fra neste knappen

packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-doc.component.html, packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-smaller-sections-example-1/empty-states-smaller-sections-example.component-1.html, packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-smaller-sections-example-2/empty-states-smaller-sections-example-2.component.html
=> chore(empty-state-doc): design tweaks

packages/components/components/elvis-datepicker/CHANGELOG.json, packages/components/components/elvis-datepicker/package.json, packages/components/components/elvis-datepicker/src/react/datepickerInput.tsx
https://elvia.atlassian.net/browse/LEGO-3447
=> fix(datepicker): allow pasting date into input field

packages/components/components/elvis-accordion/CHANGELOG.json, packages/components/components/elvis-accordion/package.json, packages/components/components/elvis-accordion/src/react/elvia-accordion.tsx, packages/react-test/src/App.tsx, packages/web/src/app/dev/v2-playground/v2-playground.component.html, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3449
=> Lego 3449 accordion har ikke riktig hoyde nar is open true fra starten av

packages/elvis-colors/gulpfile.ts, packages/elvis-illustrations/CHANGELOG.json, packages/elvis-illustrations/build/colors.css, packages/elvis-illustrations/package.json, packages/elvis-illustrations/src/elvisIllustration.ts, packages/web/angular.json, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/illustrations-exhibit-details.component.html, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/illustrations-exhibit-details.component.ts, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/imageDownloadUtils.ts, packages/web/src/typings.d.ts
https://elvia.atlassian.net/browse/LEGO-3438
=> Lego 3438 illustrasjons doc laste ned illustrasjoner i dark theme

packages/elvis/percy/snapshots.js, packages/elvis/percy/utilities/grid.html
=> Lego 3455 legge til percy tester for layout

packages/web/src/app/doc-pages/brand/color-doc/color-picker/color-picker-exhibit/color-picker-exhibit.component.html, packages/web/src/app/doc-pages/brand/color-doc/color-picker/color-picker-header/color-picker-header.component.html, packages/web/src/app/doc-pages/brand/color-doc/color-picker/color-picker-header/color-picker-header.component.scss, packages/web/src/app/doc-pages/brand/color-doc/color-picker/color-picker-header/color-picker-header.component.ts, packages/web/src/app/doc-pages/brand/color-doc/color.component.html, packages/web/src/app/doc-pages/brand/icon-doc/icon-doc.component.html, packages/web/src/app/doc-pages/brand/icon-doc/icon-doc.component.scss, packages/web/src/app/doc-pages/brand/icon-doc/icon-doc.component.ts, packages/web/src/app/doc-pages/brand/icon-doc/icon-preview-filter/icon-preview-filter.component.html, packages/web/src/app/doc-pages/brand/icon-doc/icon-preview-filter/icon-preview-filter.component.scss, packages/web/src/app/doc-pages/brand/icon-doc/icon-preview-filter/icon-preview-filter.component.ts, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-details/illustrations-exhibit-details.component.ts, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-filter/illustrations-exhibit-filter.component.html, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-filter/illustrations-exhibit-filter.component.scss, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-filter/illustrations-exhibit-filter.component.ts, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list.component.html, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list.component.scss, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list.component.ts, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit.component.html, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit.component.ts, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit.service.ts, packages/web/src/app/shared/component-documentation/component-structure/component-header/component-header.component.html, packages/web/src/app/shared/local-theme-switch/local-theme-switch.component.html, packages/web/src/app/shared/local-theme-switch/local-theme-switch.component.ts
https://elvia.atlassian.net/browse/LEGO-3451
=> Lego 3451 light dark theme switch

packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/percy/utilities/grid.html, packages/elvis/src/utilities/_main.scss, packages/elvis/src/utilities/breakpoints.scss, packages/elvis/src/utilities/grid-container.scss, packages/elvis/src/utilities/grid-spacing.scss, packages/elvis/src/utilities/grid.scss
=> fix(elvis): add back the container class from Bootstrap

.github/workflows/playwright.yml, packages/components/components/elvis-datepicker/src/react/elvia-datepicker.tsx, packages/components/playwright-ct.config.ts
=> test(playwright): set images in master as reference for comparison

packages/components/components/elvis-breadcrumb/CHANGELOG.json, packages/components/components/elvis-breadcrumb/package.json, packages/components/components/elvis-breadcrumb/src/react/elvia-breadcrumb.tsx
Update breadcrumbs to be ssr safe
=> Make breadcrumbs ssr safe

.github/workflows/playwright.yml
=> chore(playwright.yml): update percy token

packages/components/components/elvis-autocomplete/CHANGELOG.json, packages/components/components/elvis-autocomplete/package.json, packages/components/components/elvis-autocomplete/src/react/config.ts, packages/components/components/elvis-autocomplete/src/react/elvia-autocomplete.test.tsx, packages/components/components/elvis-autocomplete/src/react/elvia-autocomplete.tsx, packages/components/components/elvis-autocomplete/src/react/elvia-autocomplete.types.tsx, packages/components/components/elvis-autocomplete/src/react/utils/filterItems.ts, packages/web/src/app/doc-pages/components/autocomplete-doc/autocomplete-ceg/autocomplete-ceg.component.ts, packages/web/src/app/doc-pages/components/autocomplete-doc/autocomplete-data.ts, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3440
=> Lego 3440 autocomplete stotte at dropdownen apnes nar autocomplete far fokus

packages/components/components/elvis-stepper/CHANGELOG.json, packages/components/components/elvis-stepper/package.json, packages/components/components/elvis-stepper/src/react/styledComponents.tsx
https://elvia.atlassian.net/browse/LEGO-3466
=> feat(stepper): remove max-width but keep width of steps

packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/src/components/form/input.scss
https://elvia.atlassian.net/browse/LEGO-3467
=> fix(text-field): remove focus state when readonly

README.md
https://elvia.atlassian.net/browse/LEGO-3462
=> docs(README): update content

packages/components/components/elvis-header/CHANGELOG.json, packages/components/components/elvis-header/package.json, packages/components/components/elvis-header/src/react/themeUtils.ts, packages/web/src/app/shell/header/header.component.ts
https://elvia.atlassian.net/browse/LEGO-3476
=> Lego 3476 header dark theme legger theme pa feil element

packages/components/components/elvis-breadcrumb/CHANGELOG.json, packages/components/components/elvis-breadcrumb/package.json, packages/components/components/elvis-breadcrumb/src/react/styledComponents.tsx, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3474
=> chore(breadcrumb): replace styled-components with @emotion

packages/web/src/app/doc-pages/brand/icon-doc/icon-preview/icon-preview.component.scss
https://elvia.atlassian.net/browse/LEGO-3479
=> fix(icon-preview): grid spacing when few results

packages/components/components/elvis-popover/CHANGELOG.json, packages/components/components/elvis-popover/package.json, packages/components/components/elvis-popover/src/react/config.ts, packages/components/components/elvis-popover/src/react/elvia-popover.tsx, packages/components/components/elvis-popover/src/react/elviaPopover.types.tsx, packages/components/components/elvis-popover/src/react/styledComponents.tsx, packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/src/utilities/typography.scss, packages/web/src/app/dev/v2-playground/v2-playground.component.html, packages/web/src/app/doc-pages/brand/typography-doc/abbreviation-example-ceg/abbreviation-example-ceg.component.html, packages/web/src/app/doc-pages/brand/typography-doc/abbreviation-example-ceg/abbreviation-example-ceg.component.ts, packages/web/src/app/doc-pages/brand/typography-doc/typography-doc.component.html, packages/web/src/app/doc-pages/brand/typography-doc/typography-doc.component.ts, packages/web/src/app/doc-pages/components/popover-doc/popover-data.ts, packages/web/src/app/doc-pages/tools/utilities-doc/utility-groups-data.ts
https://elvia.atlassian.net/browse/LEGO-3487
=> Lego 3487 forkortelse stotte i elvis og popover

packages/components/package.json, yarn.lock
=> chore(deps): update @testing-library/dom

packages/components/components/elvis-modal/CHANGELOG.json, packages/components/components/elvis-modal/package.json, packages/components/components/elvis-modal/src/react/styledComponents.tsx
https://elvia.atlassian.net/browse/LEGO-3494
=> fix(modal): overflow on mobile

packages/components/components/elvis-accordion/CHANGELOG.json, packages/components/components/elvis-accordion/package.json, packages/components/components/elvis-accordion/src/react/elvia-accordion.spec.tsx, packages/components/components/elvis-accordion/src/react/elvia-accordion.tsx, packages/components/components/elvis-accordion/src/react/styledComponents.tsx, yarn.lock
=> Accordion: @emotion, isOpen fix, percy test update

packages/components/build/dts.plugin.ts, packages/components/build/esbuild.config.ts, packages/components/build/toolbox-build.config.ts
https://elvia.atlassian.net/browse/LEGO-3490
=> feat(build): separate toolbox build for treeshaking

packages/components/components/elvis-modal/CHANGELOG.json, packages/components/components/elvis-modal/package.json, packages/components/components/elvis-modal/src/react/config.ts
https://elvia.atlassian.net/browse/LEGO-3502
=> fix(modal): noPadding prop in web components

packages/components/components/elvis-modal/CHANGELOG.json, packages/components/components/elvis-modal/package.json, packages/components/components/elvis-modal/src/react/elvia-modal.spec.tsx, packages/components/components/elvis-modal/src/react/elvia-modal.test.tsx, packages/components/components/elvis-modal/src/react/elvia-modal.tsx, packages/components/components/elvis-modal/src/react/styledComponents.tsx, packages/components/components/elvis-toolbox/CHANGELOG.json, packages/components/components/elvis-toolbox/package.json, packages/components/components/elvis-toolbox/src/components/overlay/overlayStyles.ts, packages/web/src/app/dev/v2-playground/v2-playground.component.html, yarn.lock
=> Lego 3509 modal blurry text i text area som overflower inne i en modal

packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/src/components/form/input.scss
https://elvia.atlassian.net/browse/LEGO-3493
=> Lego 3493 input invalid css selector

packages/web/src/app/doc-pages/tools/team-symbol-doc/team-symbol-generator/symbolHelpers.ts
https://elvia.atlassian.net/browse/LEGO-3522
=> fix(web): use rgb in team symbol generator

packages/web/src/app/doc-pages/tools/team-symbol-doc/team-symbol-generator/symbolHelpers.ts, packages/web/src/app/doc-pages/tools/team-symbol-doc/team-symbol-generator/team-symbol-generator.component.ts
=> fix(web): fix xml error when opening team symbol

packages/components/build/esbuild-plugin-emotion.ts, packages/components/build/esbuild.config.ts, packages/components/package.json, yarn.lock
=> feat(build): add @emotion/babel-plugin

packages/components/components/elvis-box/CHANGELOG.json, packages/components/components/elvis-box/package.json, packages/components/components/elvis-box/src/react/styledComponents.tsx, yarn.lock
=> chore(box): migrate to @emotion, fix border radius

packages/components/components/elvis-carousel/CHANGELOG.json, packages/components/components/elvis-carousel/package.json, packages/components/components/elvis-carousel/src/react/StyledComponents.tsx, yarn.lock
=> chore(carousel): migrate to @emotion

packages/components/components/elvis-chip/CHANGELOG.json, packages/components/components/elvis-chip/package.json, packages/components/components/elvis-chip/src/react/styledComponents.tsx, yarn.lock
=> chore(chip): migrate to @emotion

.github/workflows/publishToNpm.yml
=> chore(ci): make publishToNpm workflow cancel in progress run if new trigger

packages/components/build/esbuild.config.ts, packages/components/build/toolbox-build.config.ts, packages/components/components/elvis-stepper/CHANGELOG.json, packages/components/components/elvis-stepper/package.json, packages/components/components/elvis-stepper/src/react/VerticalStepElement.tsx, packages/components/components/elvis-stepper/src/react/elvia-stepper-horizontal.tsx, packages/components/components/elvis-stepper/src/react/styledComponents.tsx, packages/components/components/elvis-toolbox/CHANGELOG.json, packages/components/components/elvis-toolbox/package.json, packages/components/components/elvis-toolbox/src/components/backdrop/transparentBackdrop.tsx, packages/components/components/elvis-toolbox/src/components/button/button.tsx, packages/components/components/elvis-toolbox/src/components/button/iconButton.tsx, packages/components/components/elvis-toolbox/src/components/form-field/errorStyles.tsx, packages/components/components/elvis-toolbox/src/components/form-field/formFieldStyles.tsx, packages/components/components/elvis-toolbox/src/components/overlay/overlayStyles.ts, packages/components/components/elvis-toolbox/src/components/tooltip/tooltip.tsx, packages/components/components/elvis-toolbox/src/components/visually-hidden/visuallyHidden.tsx, yarn.lock
=> chore: migrate toolbox and stepper to @emotion

packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-class-list/empty-states-class-list.component.html, packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-class-list/empty-states-class-list.component.ts, packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-doc.component.html, packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-full-page-example/empty-states-full-page-example.component.html, packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-full-page-example/empty-states-full-page-example.component.scss
https://elvia.atlassian.net/browse/LEGO-3513
=> feat(web): add spacing values to empty state docs

packages/web/src/app/doc-pages/components/accordion-doc/accordion-group-ceg/accordion-group-ceg.component.html
https://elvia.atlassian.net/browse/LEGO-3516
=> fix(web): add divider on top and bottom and add margin to accordin group

packages/web/src/app/doc-pages/tools/team-symbol-doc/svg-abbreviation-popover/svg-abbreviation-popover.component.html, packages/web/src/app/doc-pages/tools/team-symbol-doc/svg-abbreviation-popover/svg-abbreviation-popover.component.ts, packages/web/src/app/doc-pages/tools/team-symbol-doc/team-symbol-generator/team-symbol-generator.component.html, packages/web/src/app/doc-pages/tools/team-symbol-doc/team-symbol-generator/team-symbol-generator.component.ts, packages/web/src/app/doc-pages/tools/team-symbol-doc/why-svg-popover/why-svg-popover.component.html, packages/web/src/app/doc-pages/tools/team-symbol-doc/why-svg-popover/why-svg-popover.component.scss, packages/web/src/app/doc-pages/tools/team-symbol-doc/why-svg-popover/why-svg-popover.component.ts
- [n/a] Bumpet package?
- [n/a] Updated changelog?
- [n/a] Correct date in changelog?
I have created two small popover components in the Symbol generator.
Oppgave: https://elvia.atlassian.net/browse/LEGO-3530?atlOrigin=eyJpIjoiZGY3YjUxOTA2YTdlNGM0MDg4ODk5MDYzOGYxMWQwNDYiLCJwIjoiaiJ9
=> LEGO-3530 Team Symbol Generator – oppdatere med SVG forklaring

packages/components/components/elvis-accordion/CHANGELOG.json, packages/components/components/elvis-accordion/package.json, packages/components/components/elvis-accordion/src/react/elvia-accordion.tsx, packages/components/components/elvis-accordion/src/react/styledComponents.tsx
https://elvia.atlassian.net/browse/LEGO-3527
=> fix(accordion): remove spacing below closed accordion

packages/components/components/elvis-header/CHANGELOG.json, packages/components/components/elvis-header/package.json, packages/components/components/elvis-toolbox/CHANGELOG.json, packages/components/components/elvis-toolbox/package.json, packages/components/components/elvis-toolbox/src/components/button/button.tsx, yarn.lock
=> fix(toolbox&header): make ButtonBase forwardRef

.github/workflows/runComponentTests.yml
=> feat(ci:runComponentTests): rerun tests on error

packages/components/components/elvis-accordion/CHANGELOG.json, packages/components/components/elvis-accordion/package.json, packages/components/components/elvis-accordion/src/react/elvia-accordion.tsx, packages/components/components/elvis-accordion/src/react/styledComponents.tsx
https://elvia.atlassian.net/browse/LEGO-3534
=> fix(accordion): dont rotate icon in open/close label

packages/web/src/app/doc-pages/components/button-doc/button-doc.component.html, packages/web/src/app/doc-pages/components/button-doc/button-size-ceg/button-size-ceg.component.html, packages/web/src/app/doc-pages/components/button-doc/button-type-danger-ceg/button-type-danger-ceg.component.html, packages/web/src/app/doc-pages/components/button-doc/button-type-icon-ceg/button-type-icon-ceg.component.html, packages/web/src/app/doc-pages/components/button-doc/button-type-icon-circled-ceg/button-type-icon-circled-ceg.component.html, packages/web/src/app/doc-pages/components/button-doc/button-type-primary-ceg/button-type-primary-ceg.component.html, packages/web/src/app/doc-pages/components/button-doc/button-type-secondary-ceg/button-type-secondary-ceg.component.html, packages/web/src/app/doc-pages/components/button-doc/button-type-tertiary-ceg/button-type-tertiary-ceg.component.html, packages/web/src/app/doc-pages/components/content-loader-doc/content-loader-ceg/content-loader-ceg.component.html, packages/web/src/app/doc-pages/components/content-loader-doc/content-loader-doc.component.html, packages/web/src/app/doc-pages/components/content-loader-doc/content-loader-text-ceg/content-loader-text-ceg.component.html, packages/web/src/app/shared/component-documentation/ceg/static-ceg/static-ceg.component.html, packages/web/src/app/shared/component-documentation/ceg/static-ceg/static-ceg.component.scss, packages/web/src/app/shared/component-documentation/ceg/static-ceg/static-ceg.component.ts
=> Lego 3539 erstatte diverse ceg inline styles med e flex e gap 16 OSV

packages/web/src/app/doc-pages/brand/icon-doc/icon-colors-ceg/icon-colors-ceg.component.html, packages/web/src/app/doc-pages/brand/icon-doc/icon-doc.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-alignment-ceg/layout-alignment-ceg.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-breakpoints-ceg/layout-breakpoints-ceg.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-doc.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-gutters-ceg/layout-gutters-ceg.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-gutters-custom-ceg/layout-gutters-custom-ceg.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-gutters-no-ceg/layout-gutters-no-ceg.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-levels-ceg/layout-levels-ceg.component.html, packages/web/src/app/doc-pages/brand/layout-doc/layout-ordering-ceg/layout-ordering-ceg.component.html, packages/web/src/app/doc-pages/components/alert-messages/alert-global-expandable-ceg/alert-global-expandable-ceg.component.html, packages/web/src/app/doc-pages/components/alert-messages/alert-messages.component.html, packages/web/src/app/doc-pages/components/context-menu-doc/context-menu-doc.component.html, packages/web/src/app/doc-pages/components/forms/search-doc/search-doc.component.html, packages/web/src/app/doc-pages/components/forms/search-doc/search-fullwidth-ceg/search-fullwidth-ceg.component.html, packages/web/src/app/doc-pages/components/forms/search-doc/search-size-medium-ceg/search-size-medium-ceg.component.html, packages/web/src/app/doc-pages/components/forms/search-doc/search-size-small-ceg/search-size-small-ceg.component.html, packages/web/src/app/doc-pages/components/popover-doc/popover-doc.component.html, packages/web/src/app/doc-pages/components/table-doc/table-doc.component.html, packages/web/src/app/doc-pages/components/table-doc/table-footnote-ceg/table-footnote-ceg.component.html, packages/web/src/app/doc-pages/components/table-doc/table-validation-row-ceg/table-validation-row-ceg.component.html, packages/web/src/app/shared/do-dont-text/do-dont-text.component.html, packages/web/src/app/shell/header/mobile-menu/mobile-menu.component.html, packages/web/src/app/shell/header/search-menu/search-menu.component.html
=> chore(web): remove use of e-w-100

packages/components/components/elvis-accordion/src/react/elvia-accordion.tsx
=> chore(accordion): remove dead outline listener

yarn.lock
=> fix(deps): update socks to fix dependabot alert

packages/web/src/app/doc-pages/components/forms/input-doc/input-options-nolabel-ceg/input-options-nolabel-ceg.component.html, packages/web/src/app/doc-pages/components/forms/radiobutton-doc/radiobutton-ceg/radiobutton-ceg.component.html, packages/web/src/app/doc-pages/components/table-doc/table-checkbox-desktop-ceg/table-checkbox-desktop-ceg.component.html, packages/web/src/app/doc-pages/components/table-doc/table-checkbox-mobile-ceg/table-checkbox-mobile-ceg.component.html, packages/web/src/app/doc-pages/components/tag-doc/tag-colored-ceg/tag-colored-ceg.component.html
JIRA-sak: https://elvia.atlassian.net/browse/LEGO-3541
=> docs: fix minor ceg issues

packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/src/components/outline.scss
=> Lego 3562 input outline pa klikk

yarn.lock
=> fix(deps): update deps to fix dependabot alert

packages/components/components/elvis-datepicker/CHANGELOG.json, packages/components/components/elvis-datepicker/src/react/calendar/calendarStyles.tsx, packages/components/components/elvis-slider/CHANGELOG.json, packages/components/components/elvis-slider/package.json, packages/components/components/elvis-slider/src/react/styledComponents.tsx, packages/web/src/app/dev/v2-playground/v2-playground.component.scss
1. Fix `:first-child` warning in slider.
2. Fix `:first-child` warning in datepicker, but without publishing new datepicker version as I assume we will be publishing more fixes for that package soon. 
3. Remove some unused style from dev playground.
=> Fix emotion ssr warning

.github/workflows/publishToNpm.yml
=> feat(publishToNpm.yml): rerun tests if failed

packages/components/components/elvis-datepicker-range/CHANGELOG.json, packages/components/components/elvis-datepicker-range/package.json, packages/components/components/elvis-datepicker-range/src/react/config.ts
=> fix(datepicker-range): make prop isVertical boolean in wrapper config

packages/components/components/elvis-header/CHANGELOG.json, packages/components/components/elvis-header/package.json, packages/components/components/elvis-header/src/react/elviaApps.ts, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3556
=> feat(header): add Co and Oa, remove Mc from AppDrawer

packages/elvis/CHANGELOG.json, packages/elvis/src/components/button/button-helpers.scss
=> feat(elvis): support modifier classes on mobile

packages/elvis/CHANGELOG.json, packages/elvis/src/components/outline.scss
=> fix(elvis): remove outline from focused text area

packages/components/components/elvis-datepicker-range/src/react/elvia-datepicker-range.spec.tsx, packages/components/components/elvis-datepicker/src/react/elvia-datepicker.spec.tsx
=> test(datepicker+range): add/update percy tests

packages/components/components/elvis-breadcrumb/src/react/elvia-breadcrumb.spec.tsx, packages/components/components/elvis-segmented-control/src/react/elvia-segmented-control.spec.tsx, packages/components/components/elvis-tabs/src/react/elvia-tabs.spec.tsx
=> test(breadcrumb, segmented-control, tabs): add percy tests

packages/components/components/elvis-card/src/react/elvia-card.spec.tsx, packages/components/components/elvis-card/src/react/elvia-card.test.tsx, packages/components/components/elvis-dropdown/src/react/elvia-dropdown.spec.tsx, packages/components/components/elvis-dropdown/src/react/elvia-dropdown.test.tsx, packages/components/components/elvis-timepicker/src/react/elvia-timepicker.spec.tsx
=> test(card, dropdown, timepicker): add percy tests

packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/src/components/form/checkbox.scss, packages/elvis/src/components/form/radiobutton.scss, packages/elvis/src/components/form/toggle.scss
https://elvia.atlassian.net/browse/LEGO-3578
=> fix(elvis): invalid focus css selectors for checkbox, radiobutton, toggle

packages/components/components/elvis-toolbox/CHANGELOG.json, packages/components/components/elvis-toolbox/package.json, packages/elvis-colors/CHANGELOG.md, packages/elvis-colors/package.json
=> chore: mark colors as sideeffect-free, toolbox as ESM

packages/components/components/elvis-popover/CHANGELOG.json, packages/components/components/elvis-popover/package.json, packages/components/components/elvis-popover/src/react/styledComponents.tsx
https://elvia.atlassian.net/browse/LEGO-3570
=> Lego 3570 popover trigger container setter alle div er innenfor til display flex

packages/web/src/app/shared/component-documentation/ceg/ceg.component.html, packages/web/src/app/shared/component-documentation/ceg/controls-popover/controls-popover.component.html, packages/web/src/app/shared/component-documentation/ceg/controls-popover/controls-popover.component.ts
https://elvia.atlassian.net/browse/LEGO-3571
=> fix(ceg): slot toggle in mobile view

packages/web/src/app/doc-pages/components/button-doc/button-type-primary-ceg/button-type-primary-ceg.component.html
https://elvia.atlassian.net/jira/software/c/projects/LEGO/boards/60?selectedIssue=LEGO-3537
=> chore: add aria live to button ceg

packages/web/src/app/doc-pages/cms/cms-page/cms-page.component.html, packages/web/src/app/doc-pages/components/components-doc.component.html
https://elvia.atlassian.net/browse/LEGO-3582
=> fix(web): overview page title alignments

packages/web/src/app/home/front-page-changelog/front-page-changelog.component.html
https://elvia.atlassian.net/browse/LEGO-3583
=> fix(web): front page changelog url for illustrations

packages/components/components/elvis-dropdown/src/react/elvia-dropdown.test.tsx
=> test(dropdown): skip flaky test

README.md, package.json, packages/components/README.md, packages/components/components/elvis-header/src/react/elviaApps.ts, packages/elvis/README.md, packages/web/src/app/doc-pages/brand/illustrations-doc/illustrations-exhibit/illustrations-exhibit-list/illustrations-exhibit-list.component.ts, renovate.json, yarn.lock
=> chore: remove husky and lint-staged

renovate.json
=> chore(renovate): update schedule

packages/web/src/app/doc-pages/components/alert-messages/alert-messages.component.html, packages/web/src/app/doc-pages/components/alert-messages/alert-messages.component.ts, packages/web/src/app/doc-pages/components/toast-doc/toast-doc.component.ts, packages/web/src/app/doc-pages/components/tooltip-doc/tooltip-doc.component.ts
https://elvia.atlassian.net/browse/LEGO-3590
=> docs(alert): improve type table, fix grammar

packages/elvis/.internal/classlist.json, packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/percy/components/table.html, packages/elvis/src/components/table.scss, packages/web/src/app/dev/v2-playground/v2-playground.component.html
https://elvia.atlassian.net/browse/LEGO-3532
=> Lego 3532 table elvis fungerer ikke med table inni en annen table

packages/web/src/app/shell/page-with-sidenav/page-with-sidenav.component.html
https://elvia.atlassian.net/browse/LEGO-3591
=> fix(web): back button link

packages/elvis-typography/CHANGELOG.md, packages/elvis-typography/package.json, packages/elvis-typography/src/elviaTypography.ts, packages/elvis/CHANGELOG.json, packages/elvis/package.json, yarn.lock
Font-size, letter-spacing, px -> rem
- Test ved å endre font-size i browseren
=> feat(typography): Font-size, letter-spacing, px -> rem

packages/web/src/app/doc-pages/components/header-doc/header-doc.component.html
Added documentation for external header
=> docs(header): added documentation for external header

packages/elvis/tasks/styles.mjs
https://elvia.atlassian.net/browse/LEGO-3589
=> chore(elvis): disable mixed-decls warnings in scss build

packages/elvis/CHANGELOG.json
=> chore(elvis): set changelog 20.0.0 entry to private

yarn.lock
=> fix(deps): axios dependabot alert

packages/web/src/app/shell/header/header.component.html
=> fix(web): warning about @for track

.vscode/extensions.json, .vscode/settings.json
=> chore: update recommended vscode extension list

packages/elvis/CHANGELOG.json, packages/elvis/src/components/form/input.scss, packages/web/src/app/doc-pages/components/dropdown-doc/dropdown-data.ts, packages/web/src/app/doc-pages/components/forms/input-doc/input-doc.component.html
Removed fallback on input animation
=> Lego 3600 input fjerne loading animation fallback

packages/elvis/.internal/classlist.json, packages/elvis/CHANGELOG.json, packages/elvis/percy/components/input.html, packages/elvis/src/components/form/input.scss
https://elvia.atlassian.net/browse/LEGO-3609
=> feat(input): new class e-input---active

packages/web/src/app/dev/v2-playground/v2-playground.component.html, packages/web/src/app/doc-pages/components/context-menu-doc/context-menu-icons-ceg/context-menu-icons-ceg.component.html, packages/web/src/app/doc-pages/components/context-menu-doc/context-menu-selectable-ceg/context-menu-selectable-ceg.component.html
=> chore(web): remove old elvis-icon uses

packages/elvis-assets-icons/CHANGELOG.md, packages/elvis-assets-icons/package.json
=> chore(assets-icons): mark package as side-effect free

packages/components/components/elvis-popover/CHANGELOG.json, packages/components/components/elvis-popover/package.json, packages/components/components/elvis-popover/src/react/elvia-popover.tsx, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3618
=> fix(popover): unexpected content slot remounting

packages/web/src/app/doc-pages/brand/icon-doc/icon-preview/icon-preview.component.ts
https://elvia.atlassian.net/browse/LEGO-3629
=> chore(icon-preview-filter): allow searching camelCase

packages/elvis/.internal/classlist.json, packages/elvis/CHANGELOG.json, packages/elvis/package.json, packages/elvis/src/components/form/input.scss, packages/web/src/app/dev/v2-playground/v2-playground.component.html
This class makes using an icon with a tooltip inside the input easier.
https://elvia.atlassian.net/browse/LEGO-3633?atlOrigin=eyJpIjoiYmNjMGQ3NjZmMTI0NGI0NzhlY2Q5ZjFhOWU1MjA0MmUiLCJwIjoiaiJ9
=> Lego 3633 input egen klasse for ikon i input

README.md, packages/components/README.md, packages/elvis-assets-icons/README.md, packages/elvis-colors/README.md, packages/elvis-typography/README.md
https://elvia.atlassian.net/browse/LEGO-3625
=> docs: update README files

packages/components/components/elvis-header/CHANGELOG.json, packages/components/components/elvis-header/package.json, packages/components/components/elvis-header/src/react/elviaApps.ts, yarn.lock
Added Projectportal app to the header component and changed related dependencies.
=> Add Projectportal app on header component and change dependencies

tsconfig.json
https://fortelvia.test-elvia.io/shared?chatId=602ae80f-bea3-401f-8d00-677690276d61&sharedChatId=e31f8fda-e873-437f-a047-c5f8b9afaecf
=> chore(tsconfig): update based on fortelvia recommendations

packages/components/components/elvis-app-bridge/src/react/elvia-app-bridge.test.tsx, packages/components/components/elvis-segmented-control/src/react/elvia-segmented-control.spec.tsx
=> test(app-bridge): test that current domain link is hidden

packages/web/src/app/core/services/cms/cms-transform.service.ts, packages/web/src/app/doc-pages/cms/cms-page/cms-page.component.scss, packages/web/src/app/doc-pages/cms/cms-page/cms-page.component.ts
https://elvia.atlassian.net/browse/LEGO-3654
=> fix(web): missing icon

packages/components/components/elvis-header/CHANGELOG.json, packages/components/components/elvis-header/package.json, packages/components/components/elvis-header/src/react/appList/appListStyles.tsx
This PR sets the text color so that links don't inherit the browser's default link color.
https://elvia.atlassian.net/browse/LEGO-3655
=> Lego 3655 app drawer lenkene blir bla

packages/web/src/app/doc-pages/brand/color-doc/color-token-table/color-token-subtable/color-token-subtable.component.html, packages/web/src/app/doc-pages/brand/color-doc/color-token-table/color-token-table.component.scss
This PR ensures there is 16px margin + 16px grid gap between each subtable.
DOM is now like this:
- subtable
- 16px margin
- divider here
- 16px gap
- subtable
See also: https://www.figma.com/design/S7hXnDqBIr6VTSWJx1OQlx/Design.elvia.io?node-id=18027-22975&m=dev
=> LEGO-3658: Ujevn alignment på colors siden på design.elvia.io

packages/components/components/elvis-chip/CHANGELOG.json, packages/components/components/elvis-chip/package.json, packages/components/components/elvis-pagination/CHANGELOG.json
=> 18092024 chip

packages/vue-test/package.json, packages/vue-test/vite.config.ts, yarn.lock
=> chore(vue-test): remove plugin-commonjs

packages/components/components/elvis-chip/CHANGELOG.json, packages/components/components/elvis-chip/package.json, packages/components/components/elvis-chip/src/react/elvia-chip.tsx, packages/components/components/elvis-chip/src/react/styledComponents.tsx, packages/web/src/app/dev/v2-playground/v2-playground.component.html, packages/web/src/app/doc-pages/components/chip-doc/chip-ceg/chip-ceg.component.ts, packages/web/src/app/doc-pages/components/chip-doc/chip-doc.component.html, yarn.lock
https://elvia.atlassian.net/browse/LEGO-3665
This PR ensures that the legend chip does not change colors while disabled. It also ensures that the loading dots are at 30 opacity while it is loading and disabled (so that it matches the marker style)
=> LEGO-3665: chip disabled legend chip burde ikke fa hover states nar disabled

packages/web/src/app/core/services/localization.service.ts
=> fix(web): set lang attr when locale changes

packages/components/components/elvis-app-bridge/CHANGELOG.json, packages/components/components/elvis-app-bridge/package.json, packages/components/components/elvis-app-bridge/src/react/getLinks.ts
Adds "Jordfeil" (aka MSIj) to the App Bridge
=> LEGO-3668 App Bride: legge til jordfeil

packages/web/src/app/doc-pages/components/accordion-doc/accordion-doc.component.ts, packages/web/src/app/doc-pages/components/breadcrumb-doc/breadcrumb-doc.component.ts, packages/web/src/app/doc-pages/components/card-doc/card-doc.component.ts, packages/web/src/app/doc-pages/components/carousel-doc/carousel-doc.component.ts, packages/web/src/app/doc-pages/components/content-loader-doc/content-loader-doc.component.ts, packages/web/src/app/doc-pages/components/divider-doc/divider-doc.component.ts, packages/web/src/app/doc-pages/components/file-upload-doc/file-upload-doc.component.ts, packages/web/src/app/doc-pages/components/forms/checkbox-doc/checkbox-doc.component.ts, packages/web/src/app/doc-pages/components/forms/draganddrop-doc/draganddrop-doc.component.ts, packages/web/src/app/doc-pages/components/forms/radiobutton-doc/radiobutton-doc.component.ts, packages/web/src/app/doc-pages/components/forms/segmented-controls-doc/segmented-controls-doc.component.ts, packages/web/src/app/doc-pages/components/forms/timepicker-doc/timepicker-doc.component.ts, packages/web/src/app/doc-pages/components/forms/toggle-doc/toggle-doc.component.ts, packages/web/src/app/doc-pages/components/link-doc/link-doc.component.ts, packages/web/src/app/doc-pages/components/list-doc/list-doc.component.ts, packages/web/src/app/doc-pages/components/modal-doc/modal-doc.component.ts, packages/web/src/app/doc-pages/components/progressbar-doc/progressbar-doc.component.ts, packages/web/src/app/doc-pages/components/radio-filter-doc/radio-filter-doc.component.ts, packages/web/src/app/doc-pages/components/stepper-doc/stepper-doc.component.ts, packages/web/src/app/doc-pages/components/tabs-doc/tabs-doc.component.ts, packages/web/src/app/doc-pages/components/tag-doc/tag-doc.component.ts, packages/web/src/app/shared/component-documentation/component-structure/component-subsubsection/component-subsubsection.component.ts
=> Unexpected empty source

packages/web/src/app/doc-pages/brand/typography-doc/typography-example-exhibit/typography-example-exhibit-filter/typography-example-exhibit-filter.component.ts, packages/web/src/app/shared/component-documentation/ceg/code-generator/code-viewer/code-viewer.component.ts, packages/web/src/app/shared/component-documentation/ceg/controls-popover/controls-popover.component.ts, packages/web/src/app/shared/component-documentation/ceg/controls/checkbox/checkbox.component.ts, packages/web/src/app/shared/component-documentation/ceg/controls/controls.component.html, packages/web/src/app/shared/component-documentation/ceg/controls/controls.component.ts, packages/web/src/app/shared/component-documentation/ceg/controls/counter/counter.component.ts, packages/web/src/app/shared/component-documentation/ceg/controls/radio-group/radio-group.component.ts, packages/web/src/app/shared/component-documentation/ceg/controls/switch/switch.component.ts, packages/web/src/app/shared/component-documentation/ceg/controls/text/text.component.ts, packages/web/src/app/shared/component-documentation/ceg/type-switcher/type-switcher.component.ts, packages/web/src/app/shared/component-documentation/component-properties-table/property-search-input/property-search-input.component.ts, packages/web/src/app/shell/header/mobile-menu/mobile-menu.component.ts, packages/web/src/app/shell/header/search-menu/search-menu.component.ts, packages/web/src/app/shell/header/theme-switch/theme-switch.component.ts
- [n/a] Bumpet package?
- [n/a] Updated changelog?
- [n/a] Correct date in changelog?
In this PR I followed the _[Migration to output function](https://angular.dev/reference/migrations/outputs)_ guide and ran the command:
```
ng generate @angular/core:output-migration
```
I also fixed two `@angular-eslint/no-output-native` linting errors.
=> LEGO-3682 Web – migration to output function

packages/elvis/CHANGELOG.json, packages/elvis/package.json, yarn.lock
Task: https://elvia.atlassian.net/browse/LEGO-3692
In this PR I only bump the version of Elvis, thereby triggering a new release to NPM.
This release includes the changes found in these tasks:
- https://elvia.atlassian.net/browse/LEGO-3507
- https://elvia.atlassian.net/browse/LEGO-3690
- https://elvia.atlassian.net/browse/LEGO-3693
- https://elvia.atlassian.net/browse/LEGO-3694
=> LEGO-3692: Publish Elvis 21.0.0

packages/web/src/app/doc-pages/components/alert-messages/alert-messages.component.ts, packages/web/src/app/doc-pages/components/forms/input-doc/input-doc.component.ts, packages/web/src/app/doc-pages/components/forms/timepicker-doc/timepicker-ceg/timepicker-ceg.component.ts, packages/web/src/app/doc-pages/components/spotlight-doc/spotlight-ceg/spotlight-ceg.component.ts, packages/web/src/app/shared/component-documentation/ceg/ceg.component.html, packages/web/src/app/shared/component-documentation/ceg/ceg.component.ts, packages/web/src/app/shared/component-documentation/component-properties-table/property-search-input/property-search-input.component.ts, packages/web/src/app/shared/feedback/feedback.component.ts, packages/web/src/app/shared/navbar/desktop-navbar/desktop-navbar.component.ts, packages/web/src/app/shell/header/search-menu/search-menu.component.ts
Ran: `ng generate @angular/core:signal-queries-migration`
See: https://angular.dev/reference/migrations/signal-queries
=> Migration to signal queries

packages/web/src/app/shell/page-with-sidenav/page-with-sidenav.component.html
=> delete missing app-feedback

packages/web/eslint.config.js, packages/web/src/app/doc-pages/about/contact/contact.component.html, packages/web/src/app/doc-pages/brand/color-doc/color-picker/color-picker-color-list/color-picker-color-list.component.html, packages/web/src/app/doc-pages/brand/color-doc/color-picker/color-picker-exhibit/color-picker-exhibit.component.html, packages/web/src/app/doc-pages/components/thumbnail-doc/thumbnail-doc.component.html, packages/web/src/app/doc-pages/patterns/empty-states-doc/empty-states-class-list/empty-states-class-list.component.html, packages/web/src/app/home/front-page-changelog/front-page-changelog.component.html, packages/web/src/app/shell/header/search-menu/search-menu.component.html
=> chore(eslint): add prefer-contextual-for-variables

packages/web/src/app/shared/component-documentation/component-related/component-related.component.ts
=> add missing InlineSvgComponent import

packages/react-test/package.json, packages/vue-test/package.json, packages/vue-test/src/views/Components.vue, yarn.lock
=> deps: update to vite 6

package.json, packages/components/components/elvis-toolbox/package.json, packages/components/package.json, packages/elvis-assets-icons/package.json, packages/elvis-colors/package.json, packages/elvis-icons/package.json, packages/elvis-typography/package.json, packages/react-test/package.json, packages/vue-test/package.json, packages/web/package.json, yarn.lock
=> 20250403 yarn

.github/workflows/azure-static-web-apps-nice-sea-07f2e0703.yml
=> remove install step

.github/workflows/azure-static-web-apps-nice-sea-07f2e0703.yml
Reverts 3lvia/designsystem#3607
=> Revert "Update azure-static-web-apps-nice-sea-07f2e0703.yml"

.github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
=> Oppdatere workflow

.github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
=> legge til repo_token: ${{ secrets.GITHUB_TOKEN }}

.github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
=> 20250407 b

.github/workflows/azure-static-web-apps-lemon-dune-011329d03.yml
=> comment  github_id_token

.gitignore, README.md, packages/components/README.md, packages/elvis/README.md, packages/web/README.md, packages/web/package.json, packages/web/src/app/shell/header/header.component.ts, packages/web/src/app/shell/header/mobile-menu/mobile-menu.component.ts, yarn.lock
=> Update docs to reflect Azure

.github/workflows/playwright.yml
=> Alert autofix 242

.github/workflows/publishToNpm.yml
=> Alert autofix 244

packages/web/src/app/doc-pages/components/empty-state-doc/empty-state-doc.component.html
=> docs(empty-state-doc): include Text suggestion in usage section
